
WebDKP_Log = {
	["Taoren, the Soul Burner 2012-12-05 21:19:37"] = {
		["awarded"] = {
			["Haronies"] = {
				["class"] = "Hunter",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Haronies",
			},
		},
		["zone"] = "Terrace of Endless Spring",
		["date"] = "2012-12-05 21:19:37",
		["reason"] = "Taoren, the Soul Burner",
		["foritem"] = "true",
		["itemid"] = "86331",
		["awardedby"] = "Fineous",
		["points"] = -5,
		["itemlink"] = "|cffa335ee|Hitem:86331:0:0:0:0:0:0:1866929664:90:0:445|h[Taoren, the Soul Burner]|h|r",
		["tableid"] = 1,
	},
	["Heald Shield 2012-12-05 22:59:57"] = {
		["awarded"] = {
			["Crymlink"] = {
				["name"] = "Crymlink",
				["class"] = "Paladin",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-05 22:59:57",
		["reason"] = "Heald Shield",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = -1,
		["itemlink"] = "Heald Shield",
		["tableid"] = 1,
	},
	["Helm of the Shadowy Vanquisher 2012-12-05 21:54:34"] = {
		["awarded"] = {
			["Elunniakk"] = {
				["class"] = "Rogue",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Elunniakk",
			},
		},
		["zone"] = "Terrace of Endless Spring",
		["date"] = "2012-12-05 21:54:34",
		["reason"] = "Helm of the Shadowy Vanquisher",
		["foritem"] = "true",
		["itemid"] = "89234",
		["awardedby"] = "Fineous",
		["points"] = -1,
		["itemlink"] = "|cffa335ee|Hitem:89234:0:0:0:0:0:0:1427209344:90:0:445|h[Helm of the Shadowy Vanquisher]|h|r",
		["tableid"] = 1,
	},
	["Breastplate of the Kings' Guard 2012-12-05 23:23:55"] = {
		["awarded"] = {
			["Cânìtänk"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Cânìtänk",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-05 23:23:55",
		["reason"] = "Breastplate of the Kings' Guard",
		["foritem"] = "true",
		["itemid"] = "87048",
		["awardedby"] = "Fineous",
		["points"] = -4,
		["itemlink"] = "|cffa335ee|Hitem:87048:0:0:0:0:0:0:1617121280:90:0:445|h[Breastplate of the Kings' Guard]|h|r",
		["tableid"] = 1,
	},
	["Jade Courtesan Figurine 2012-12-05 22:18:35"] = {
		["awarded"] = {
			["Crymlink"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Crymlink",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-05 22:18:35",
		["reason"] = "Jade Courtesan Figurine",
		["foritem"] = "true",
		["itemid"] = "86045",
		["awardedby"] = "Fineous",
		["points"] = -20,
		["itemlink"] = "|cffa335ee|Hitem:86045:0:0:0:0:0:0:1405315072:90:0:445|h[Jade Courtesan Figurine]|h|r",
		["tableid"] = 1,
	},
	["Jade Warlord Figurine 2012-12-05 23:02:29"] = {
		["awarded"] = {
			["Cânìtänk"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Cânìtänk",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-05 23:02:29",
		["reason"] = "Jade Warlord Figurine",
		["foritem"] = "true",
		["itemid"] = "86046",
		["awardedby"] = "Fineous",
		["points"] = -1,
		["itemlink"] = "|cffa335ee|Hitem:86046:0:0:0:0:0:0:1418201920:90:0:445|h[Jade Warlord Figurine]|h|r",
		["tableid"] = 1,
	},
	["2B ToES 2012-12-05 21:59:02"] = {
		["awarded"] = {
			["Toscar"] = {
				["class"] = "",
				["guild"] = "Unknown",
				["name"] = "Toscar",
			},
			["Fineous"] = {
				["class"] = "Warlock",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Fineous",
			},
			["Feyà"] = {
				["name"] = "Feyà",
				["class"] = "Mage",
			},
			["Scripè"] = {
				["name"] = "Scripè",
				["class"] = "Priest",
			},
			["Crymlink"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Crymlink",
			},
			["Hayek"] = {
				["name"] = "Hayek",
				["class"] = "Warrior",
			},
			["Scyllá"] = {
				["name"] = "Scyllá",
				["class"] = "Priest",
			},
			["Lucey"] = {
				["name"] = "Lucey",
				["class"] = "Priest",
			},
			["Cânìtänk"] = {
				["name"] = "Cânìtänk",
				["class"] = "Paladin",
			},
			["Haronies"] = {
				["class"] = "Hunter",
				["guild"] = "Unknown",
				["name"] = "Haronies",
			},
			["Kattburk"] = {
				["name"] = "Kattburk",
				["class"] = "Shaman",
			},
			["Elunniakk"] = {
				["class"] = "Rogue",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Elunniakk",
			},
		},
		["zone"] = "Kun-Lai Summit",
		["date"] = "2012-12-05 21:59:02",
		["reason"] = "2B ToES",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = 10,
		["itemlink"] = "2B ToES",
		["tableid"] = 1,
	},
	["Hood of Cursed Dreams 2012-12-05 22:15:21"] = {
		["awarded"] = {
			["Elunniakk"] = {
				["name"] = "Elunniakk",
				["class"] = "Rogue",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-05 22:15:21",
		["reason"] = "Hood of Cursed Dreams",
		["foritem"] = "true",
		["itemid"] = "87029",
		["awardedby"] = "Fineous",
		["points"] = -1,
		["itemlink"] = "|cffa335ee|Hitem:87029:0:0:0:0:0:0:-2104222848:90:0:445|h[Hood of Cursed Dreams]|h|r",
		["tableid"] = 1,
	},
	["Shoulders of the Shadowy Protector 2012-12-05 21:21:24"] = {
		["awarded"] = {
			["Toscar"] = {
				["class"] = "Shaman",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Toscar",
			},
		},
		["zone"] = "Terrace of Endless Spring",
		["date"] = "2012-12-05 21:21:24",
		["reason"] = "Shoulders of the Shadowy Protector",
		["foritem"] = "true",
		["itemid"] = "89247",
		["awardedby"] = "Fineous",
		["points"] = -10,
		["itemlink"] = "|cffa335ee|Hitem:89247:0:0:0:0:0:0:2135365120:90:0:445|h[Shoulders of the Shadowy Protector]|h|r",
		["tableid"] = 1,
	},
	["2B ToES, 1B MSV HC 2012-12-05 20:59:45"] = {
		["awarded"] = {
			["Toscar"] = {
				["name"] = "Toscar",
				["class"] = "Shaman",
			},
			["Fineous"] = {
				["class"] = "Warlock",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Fineous",
			},
			["Feyà"] = {
				["name"] = "Feyà",
				["class"] = "Mage",
			},
			["lucey"] = {
				["class"] = "",
				["guild"] = "Unknown",
				["name"] = "lucey",
			},
			["Crymlink"] = {
				["name"] = "Crymlink",
				["class"] = "Paladin",
			},
			["Hayek"] = {
				["name"] = "Hayek",
				["class"] = "Warrior",
			},
			["Elunniakk"] = {
				["name"] = "Elunniakk",
				["class"] = "Rogue",
			},
			["Cânìtänk"] = {
				["name"] = "Cânìtänk",
				["class"] = "Paladin",
			},
			["Haronies"] = {
				["name"] = "Haronies",
				["class"] = "Hunter",
			},
			["Kattburk"] = {
				["class"] = "Shaman",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Kattburk",
			},
			["Scyllá"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Scyllá",
			},
		},
		["zone"] = "Terrace of Endless Spring",
		["date"] = "2012-12-05 20:59:45",
		["reason"] = "2B ToES, 1B MSV HC",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = 10,
		["itemlink"] = "2B ToES, 1B MSV HC",
		["tableid"] = 1,
	},
	["Elegon 2012-12-06 00:07:28"] = {
		["awarded"] = {
			["Toscar"] = {
				["class"] = "Shaman",
				["guild"] = "Unknown",
				["name"] = "Toscar",
			},
			["Fineous"] = {
				["class"] = "Warlock",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Fineous",
			},
			["Feyà"] = {
				["name"] = "Feyà",
				["class"] = "Mage",
			},
			["Scripè"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Scripè",
			},
			["Crymlink"] = {
				["class"] = "Paladin",
				["guild"] = "Unknown",
				["name"] = "Crymlink",
			},
			["Hayek"] = {
				["name"] = "Hayek",
				["class"] = "Warrior",
			},
			["Scyllá"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Scyllá",
			},
			["Lucey"] = {
				["name"] = "Lucey",
				["class"] = "Priest",
			},
			["Cânìtänk"] = {
				["name"] = "Cânìtänk",
				["class"] = "Paladin",
			},
			["Haronies"] = {
				["class"] = "Hunter",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Haronies",
			},
			["Kattburk"] = {
				["name"] = "Kattburk",
				["class"] = "Shaman",
			},
			["Elunniakk"] = {
				["name"] = "Elunniakk",
				["class"] = "Rogue",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-06 00:07:28",
		["reason"] = "Elegon",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = 10,
		["itemlink"] = "Elegon",
		["tableid"] = 1,
	},
	["1B MSV HC 2012-12-05 22:59:01"] = {
		["awarded"] = {
			["Toscar"] = {
				["name"] = "Toscar",
				["class"] = "Shaman",
			},
			["Fineous"] = {
				["class"] = "Warlock",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Fineous",
			},
			["Feyà"] = {
				["class"] = "Mage",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Feyà",
			},
			["Scripè"] = {
				["name"] = "Scripè",
				["class"] = "Priest",
			},
			["Crymlink"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Crymlink",
			},
			["Hayek"] = {
				["class"] = "Warrior",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Hayek",
			},
			["Scyllá"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Scyllá",
			},
			["Lucey"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Lucey",
			},
			["Cânìtänk"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Cânìtänk",
			},
			["Haronies"] = {
				["class"] = "Hunter",
				["guild"] = "Unknown",
				["name"] = "Haronies",
			},
			["Kattburk"] = {
				["class"] = "Shaman",
				["guild"] = "Unknown",
				["name"] = "Kattburk",
			},
			["Elunniakk"] = {
				["class"] = "Rogue",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Elunniakk",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-05 22:59:01",
		["reason"] = "1B MSV HC",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = 10,
		["itemlink"] = "1B MSV HC",
		["tableid"] = 1,
	},
	["Version"] = 2,
	["Girdle of Delirious Visions 2012-12-05 23:24:33"] = {
		["awarded"] = {
			["Crymlink"] = {
				["name"] = "Crymlink",
				["class"] = "Paladin",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-05 23:24:33",
		["reason"] = "Girdle of Delirious Visions",
		["foritem"] = "true",
		["itemid"] = "87056",
		["awardedby"] = "Fineous",
		["points"] = -1,
		["itemlink"] = "|cffa335ee|Hitem:87056:0:0:0:0:0:0:1360111360:90:0:445|h[Girdle of Delirious Visions]|h|r",
		["tableid"] = 1,
	},
	["Fetters of Death 2012-12-05 22:58:01"] = {
		["awarded"] = {
			["Toscar"] = {
				["class"] = "Shaman",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Toscar",
			},
		},
		["zone"] = "Mogu'shan Vaults",
		["date"] = "2012-12-05 22:58:01",
		["reason"] = "Fetters of Death",
		["foritem"] = "true",
		["itemid"] = "87034",
		["awardedby"] = "Fineous",
		["points"] = -1,
		["itemlink"] = "|cffa335ee|Hitem:87034:0:0:0:0:0:0:1324860608:90:0:445|h[Fetters of Death]|h|r",
		["tableid"] = 1,
	},
	["Kilrak, Jaws of Terror 2012-12-05 21:53:48"] = {
		["awarded"] = {
			["Cânìtänk"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Cânìtänk",
			},
		},
		["zone"] = "Terrace of Endless Spring",
		["date"] = "2012-12-05 21:53:48",
		["reason"] = "Kilrak, Jaws of Terror",
		["foritem"] = "true",
		["itemid"] = "86387",
		["awardedby"] = "Fineous",
		["points"] = -1,
		["itemlink"] = "|cffa335ee|Hitem:86387:0:0:0:0:0:0:1158773888:90:0:445|h[Kilrak, Jaws of Terror]|h|r",
		["tableid"] = 1,
	},
	["2B ToES, 1B MSV HC 2012-12-05 21:08:39"] = {
		["awarded"] = {
			["Lucey"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Lucey",
			},
		},
		["zone"] = "Terrace of Endless Spring",
		["date"] = "2012-12-05 21:08:39",
		["reason"] = "2B ToES, 1B MSV HC",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = 10,
		["itemlink"] = "2B ToES, 1B MSV HC",
		["tableid"] = 1,
	},
}
WebDKP_DkpTable = {
	["Lucey"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 40,
		["class"] = "Priest",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Toscar"] = {
		["gp_1"] = 1,
		["standby"] = 1,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 29,
		["class"] = "Shaman",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Scripè"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 30,
		["class"] = "Priest",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Fineous"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 40,
		["class"] = "Warlock",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Haronies"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 35,
		["class"] = "Hunter",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Feyà"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 40,
		["class"] = "Mage",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["lucey"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 10,
		["class"] = "Priest",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Crymlink"] = {
		["gp_1"] = 1,
		["standby"] = 1,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 18,
		["class"] = "Paladin",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Hayek"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 40,
		["class"] = "Warrior",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Scyllá"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 40,
		["class"] = "Priest",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Elunniakk"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 38,
		["class"] = "Rogue",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Kattburk"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 40,
		["class"] = "Shaman",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Cânìtänk"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["cantrim"] = false,
		["dkp_1"] = 34,
		["class"] = "Paladin",
		["ep_1"] = 0,
		["Selected"] = false,
	},
}
WebDKP_Tables = {
	["Main Table"] = {
		["id"] = 1,
	},
}
WebDKP_Loot = {
}
WebDKP_Alts = {
}
WebDKP_WebOptions = {
	["CombineAlts"] = 0,
	["TierSize"] = 50,
	["ZeroSumEnabled"] = 0,
	["TiersEnabled"] = 0,
	["LifetimeEnabled"] = 1,
}
