
WebDKP_Log = {
	["Hisek's Chrysanthemum Cape 2012-12-08 21:55:39"] = {
		["awarded"] = {
			["Cânìtänk"] = {
				["name"] = "Cânìtänk",
			},
		},
		["zone"] = "In Game Synched",
		["date"] = "2012-12-08 21:55:39",
		["reason"] = "Hisek's Chrysanthemum Cape",
		["foritem"] = "true",
		["awardedby"] = "Crymlink",
		["points"] = -1,
		["itemlink"] = "Hisek's Chrysanthemum Cape",
		["tableid"] = 1,
	},
	["Ring of the Bladed Tempest 2012-12-08 22:58:30"] = {
		["awarded"] = {
			["Hayek"] = {
				["name"] = "Hayek",
			},
		},
		["zone"] = "In Game Synched",
		["date"] = "2012-12-08 22:58:30",
		["reason"] = "Ring of the Bladed Tempest",
		["foritem"] = "true",
		["awardedby"] = "Crymlink",
		["points"] = -1,
		["itemlink"] = "Ring of the Bladed Tempest",
		["tableid"] = 1,
	},
	["Fragment of Fear Made Flesh 2012-12-08 21:54:18"] = {
		["awarded"] = {
			["Fineous"] = {
				["name"] = "Fineous",
			},
		},
		["zone"] = "In Game Synched",
		["date"] = "2012-12-08 21:54:18",
		["reason"] = "Fragment of Fear Made Flesh",
		["foritem"] = "true",
		["awardedby"] = "Crymlink",
		["points"] = -21,
		["itemlink"] = "|cffa335ee|Hitem:86156:0:0:0:0:0:0:0:90:0:0|h[Fragment of Fear Made Flesh]|h|r",
		["tableid"] = 1,
	},
}
WebDKP_DkpTable = {
	["Toscar"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 69,
		["dkp_1"] = 109,
		["class"] = "Shaman",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Kattburk"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 80,
		["dkp_1"] = 110,
		["class"] = "Shaman",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Fineous"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 80,
		["dkp_1"] = 99,
		["class"] = "Warlock",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Lucey"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 80,
		["dkp_1"] = 120,
		["class"] = "Priest",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Feyà"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 50,
		["dkp_1"] = 50,
		["class"] = "Mage",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Elunniakk"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 78,
		["dkp_1"] = 108,
		["class"] = "Rogue",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Scripè"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 69,
		["dkp_1"] = 109,
		["class"] = "Priest",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Crymlink"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 58,
		["dkp_1"] = 97,
		["class"] = "Paladin",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Hayek"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 79,
		["dkp_1"] = 118,
		["class"] = "Warrior",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Scyllá"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 80,
		["dkp_1"] = 120,
		["class"] = "Priest",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Cânìtänk"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 74,
		["dkp_1"] = 112,
		["class"] = "Paladin",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Flea"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["cantrim"] = true,
		["dkp_1"] = 0,
		["class"] = "Monk",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Haronies"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 45,
		["dkp_1"] = 45,
		["class"] = "Hunter",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Deamento"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp_1"] = 20,
		["class"] = "Paladin",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Poizen"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp"] = 40,
		["dkp_1"] = 60,
		["class"] = "Rogue",
		["ep_1"] = 0,
		["Selected"] = false,
	},
}
WebDKP_Tables = {
	["Main Table"] = {
		["id"] = 1,
	},
}
WebDKP_Loot = {
}
WebDKP_Alts = {
}
WebDKP_WebOptions = {
	["CombineAlts"] = 0,
	["TierSize"] = 50,
	["LifetimeEnabled"] = 1,
	["TiersEnabled"] = 0,
	["ZeroSumEnabled"] = 0,
}
