
WebDKP_Log = {
	["Item Trade 2012-12-11 22:32:55"] = {
		["awarded"] = {
			["Crymlink"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Crymlink",
			},
		},
		["zone"] = "Heart of Fear",
		["date"] = "2012-12-11 22:32:55",
		["reason"] = "Item Trade",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = -137,
		["itemlink"] = "Item Trade",
		["tableid"] = 1,
	},
	["Correction 2012-12-11 22:32:41"] = {
		["awarded"] = {
			["Scyllá"] = {
				["class"] = "Priest",
				["guild"] = "Unknown",
				["name"] = "Scyllá",
			},
		},
		["zone"] = "Heart of Fear",
		["date"] = "2012-12-11 22:32:41",
		["reason"] = "Correction",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = -30,
		["itemlink"] = "Correction",
		["tableid"] = 1,
	},
	["Version"] = 2,
	["Kri'tak, Imperial Scepter of the Swarm 2012-12-11 22:29:05"] = {
		["awarded"] = {
			["Scripè"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Scripè",
			},
		},
		["zone"] = "Heart of Fear",
		["date"] = "2012-12-11 22:29:05",
		["reason"] = "Kri'tak, Imperial Scepter of the Swarm",
		["foritem"] = "true",
		["itemid"] = "86227",
		["awardedby"] = "Fineous",
		["points"] = -149,
		["itemlink"] = "|cffa335ee|Hitem:86227:0:0:0:0:0:0:588338720:90:0:445|h[Kri'tak, Imperial Scepter of the Swarm]|h|r",
		["tableid"] = 1,
	},
	["Correction 2012-12-11 22:34:18"] = {
		["awarded"] = {
			["Elunniakk"] = {
				["name"] = "Elunniakk",
				["class"] = "Rogue",
			},
		},
		["zone"] = "Heart of Fear",
		["date"] = "2012-12-11 22:34:18",
		["reason"] = "Correction",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = -149,
		["itemlink"] = "Correction",
		["tableid"] = 1,
	},
	["Item Trade 2012-12-11 22:33:17"] = {
		["awarded"] = {
			["Elunniakk"] = {
				["name"] = "Elunniakk",
				["class"] = "Rogue",
			},
			["Scripè"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Scripè",
			},
		},
		["zone"] = "Heart of Fear",
		["date"] = "2012-12-11 22:33:17",
		["reason"] = "Item Trade",
		["foritem"] = "false",
		["selected"] = true,
		["awardedby"] = "Fineous",
		["points"] = 149,
		["itemlink"] = "Item Trade",
		["tableid"] = 1,
	},
	["Raid 2012-12-11 22:30:44"] = {
		["awarded"] = {
			["Toscar"] = {
				["class"] = "Shaman",
				["guild"] = "Unknown",
				["name"] = "Toscar",
			},
			["Fineous"] = {
				["class"] = "Warlock",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Fineous",
			},
			["Feyà"] = {
				["class"] = "Mage",
				["guild"] = "Unknown",
				["name"] = "Feyà",
			},
			["Lucey"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Lucey",
			},
			["Crymlink"] = {
				["class"] = "Paladin",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Crymlink",
			},
			["Hayek"] = {
				["class"] = "Warrior",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Hayek",
			},
			["Scyllá"] = {
				["class"] = "Priest",
				["guild"] = "Unknown",
				["name"] = "Scyllá",
			},
			["Kattburk"] = {
				["class"] = "Shaman",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Kattburk",
			},
			["Flea"] = {
				["name"] = "Flea",
				["class"] = "Monk",
			},
			["Cânìtänk"] = {
				["name"] = "Cânìtänk",
				["class"] = "Paladin",
			},
			["Scripè"] = {
				["class"] = "Priest",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Scripè",
			},
			["Elunniakk"] = {
				["class"] = "Rogue",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Elunniakk",
			},
		},
		["zone"] = "Heart of Fear",
		["date"] = "2012-12-11 22:30:44",
		["reason"] = "Raid",
		["foritem"] = "false",
		["awardedby"] = "Fineous",
		["points"] = 30,
		["itemlink"] = "Raid",
		["tableid"] = 1,
	},
	["Chest of the Shadowy Vanquisher 2012-12-11 22:29:53"] = {
		["awarded"] = {
			["Elunniakk"] = {
				["class"] = "Rogue",
				["guild"] = "Rapid Eye Movement",
				["name"] = "Elunniakk",
			},
		},
		["zone"] = "Heart of Fear",
		["date"] = "2012-12-11 22:29:53",
		["reason"] = "Chest of the Shadowy Vanquisher",
		["foritem"] = "true",
		["itemid"] = "89239",
		["awardedby"] = "Fineous",
		["points"] = -1,
		["itemlink"] = "|cffa335ee|Hitem:89239:0:0:0:0:0:0:856774176:90:0:445|h[Chest of the Shadowy Vanquisher]|h|r",
		["tableid"] = 1,
	},
}
WebDKP_DkpTable = {
	["Kattburk"] = {
		["dkp1"] = 0,
		["dkp"] = 140,
		["class"] = "Shaman",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 170,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Toscar"] = {
		["dkp1"] = 0,
		["dkp"] = 149,
		["class"] = "Shaman",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 179,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Elunniakk"] = {
		["dkp1"] = 0,
		["dkp"] = 148,
		["class"] = "Rogue",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 177,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Fineous"] = {
		["dkp1"] = 0,
		["dkp"] = 129,
		["class"] = "Warlock",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 159,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Elunnia"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["dkp"] = 10,
		["dkp_1"] = 10,
		["class"] = "Priest",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Feyà"] = {
		["dkp1"] = 0,
		["dkp"] = 50,
		["class"] = "Mage",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 80,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Haronies"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["dkp"] = 79,
		["dkp_1"] = 79,
		["class"] = "Hunter",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Lucey"] = {
		["dkp1"] = 0,
		["dkp"] = 160,
		["class"] = "Priest",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 190,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Crymlink"] = {
		["dkp1"] = 0,
		["dkp"] = 137,
		["class"] = "Paladin",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 30,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Hayek"] = {
		["dkp1"] = 0,
		["dkp"] = 158,
		["class"] = "Warrior",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 188,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Scyllá"] = {
		["dkp1"] = 0,
		["dkp"] = 160,
		["class"] = "Priest",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 160,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Scripè"] = {
		["dkp1"] = 0,
		["dkp"] = 149,
		["class"] = "Priest",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 179,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Flea"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["Selected"] = false,
		["cantrim"] = false,
		["dkp_1"] = 30,
		["class"] = "Monk",
		["ep_1"] = 0,
		["dkp1"] = 0,
	},
	["Cânìtänk"] = {
		["dkp1"] = 0,
		["dkp"] = 152,
		["class"] = "Paladin",
		["gp_1"] = 1,
		["cantrim"] = false,
		["dkp_1"] = 182,
		["Selected"] = false,
		["ep_1"] = 0,
		["standby"] = 0,
	},
	["Deamento"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["dkp"] = 20,
		["dkp_1"] = 20,
		["class"] = "Paladin",
		["ep_1"] = 0,
		["Selected"] = false,
	},
	["Poizen"] = {
		["gp_1"] = 1,
		["standby"] = 0,
		["dkp1"] = 0,
		["dkp"] = 60,
		["dkp_1"] = 60,
		["class"] = "Rogue",
		["ep_1"] = 0,
		["Selected"] = false,
	},
}
WebDKP_Tables = {
	["Main Table"] = {
		["id"] = 1,
	},
}
WebDKP_Loot = {
}
WebDKP_Alts = {
}
WebDKP_WebOptions = {
	["CombineAlts"] = 0,
	["TierSize"] = 50,
	["ZeroSumEnabled"] = 0,
	["TiersEnabled"] = 0,
	["LifetimeEnabled"] = 1,
}
